name: CI

on:
  push:
    branches: [develop, main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.3"
          elixir-version: "1.18.4"

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-otp-27.3-elixir-1.18.4-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-otp-27.3-elixir-1.18.4-

      - run: mix deps.get
      - run: mix precommit
      - run: mix assets.setup
      - run: mix assets.build
